# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/Counter.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/segDecoder.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/clockDiv.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/Trigger_generator.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/Distance_Calculation.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/BCD_Converter.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/segHighModule.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/Range_Sensor_Second.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/Range_Sensor.vhd}
  {C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/sources_1/new/TopDesign.vhd}
}
read_xdc {{C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/constrs_1/new/pins.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/LENOVO PC/TermProjectVersion2/TermProjectVersion2.srcs/constrs_1/new/pins.xdc}}]

synth_design -top TopDesign -part xc7a35tcpg236-1
write_checkpoint -noxdef TopDesign.dcp
catch { report_utilization -file TopDesign_utilization_synth.rpt -pb TopDesign_utilization_synth.pb }
